/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdama
 */
public class ManagePassenger extends javax.swing.JFrame {

    /**
     * Creates new form ManagePassenger
     */
    public ManagePassenger() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        pasn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBtn = new rojeru_san.complementos.RSButtonHover();
        insertBtn = new rojeru_san.complementos.RSButtonHover();
        updateBtn = new rojeru_san.complementos.RSButtonHover();
        searchBtn = new rojeru_san.complementos.RSButtonHover();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manage Passenger");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Passenger Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nationality");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Passport Number");

        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Passenger Name", "Gender", "Nationality", "Passport Number", "Phone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        deleteBtn.setText("DELETE");
        deleteBtn.setMaximumSize(new java.awt.Dimension(83, 23));
        deleteBtn.setMinimumSize(new java.awt.Dimension(83, 23));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        insertBtn.setText("INSERT");
        insertBtn.setMaximumSize(new java.awt.Dimension(83, 23));
        insertBtn.setMinimumSize(new java.awt.Dimension(83, 23));
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("UPDATE");
        updateBtn.setMaximumSize(new java.awt.Dimension(83, 23));
        updateBtn.setMinimumSize(new java.awt.Dimension(83, 23));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("SEARCH");
        searchBtn.setMaximumSize(new java.awt.Dimension(83, 23));
        searchBtn.setMinimumSize(new java.awt.Dimension(83, 23));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("<-Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)
                            .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(143, 143, 143)
                            .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(183, 183, 183)
                            .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(310, 310, 310)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pasn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(pasn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(115, 115, 115)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void table_update(){
        int c;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conr=DriverManager.getConnection("jdbc:mysql://localhost/ams","root","1234");
            String qry ="SELECT * from managepassenger";
            
            PreparedStatement pr = conr.prepareStatement(qry);
            
            ResultSet rst= pr.executeQuery();
            
            ResultSetMetaData Rss = rst.getMetaData();

            c =Rss.getColumnCount();

            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
            
            d.setRowCount(0);
            
              while(rst.next()){
                
                Object o[]={rst.getString("name"),rst.getString("gender"),rst.getString("nationality"),rst.getString("passportnumber"),rst.getString("phone")};
                d.addRow(o);
                
            }
        }catch(Exception err){
           JOptionPane.showMessageDialog(this, err);
        }
    }
    private void naActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");

            Connection conr=DriverManager.getConnection("jdbc:mysql://localhost/ams","root","1234");

            String qry = "insert into managepassenger values (?,?,?,?,?)";

            PreparedStatement pr=conr.prepareStatement(qry);

            pr.setString(1, pn.getText());
            pr.setString(2, gen.getText());
            pr.setString(3, na.getText());
            pr.setString(4, pasn.getText());
            pr.setString(5, ph.getText());

            pr.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Inserted Successfully!");
            table_update();
            pn.setText("");
            gen.setText("");
            na.setText("");
            pasn.setText("");
            ph.setText("");
            pn.requestFocus();
            conr.close();
        }catch(Exception err){
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try{
            String name= pn.getText();
            String gender=gen.getText();
            String natnlty=na.getText();
            String pasnum=pasn.getText();
            String phone=ph.getText();
            Class.forName("com.mysql.jdbc.Driver");

            Connection conr=DriverManager.getConnection("jdbc:mysql://localhost/ams","root","1234");

            //String qry= "UPDATE `manageflight` SET `source`='"+source+"',`destination`='"+des+"',`takeof`='"+tak+"',`noofseats`='"+noofseat+"'";
            String qry = "UPDATE `managepassenger` SET `name`=?, `gender`=?, `nationality`=?, `phone`=? WHERE `passportnumber`=?";

            PreparedStatement pr=conr.prepareStatement(qry);
            pr.setString(1, name);
            pr.setString(2, gender);
            pr.setString(3, natnlty);
            pr.setString(4, phone);
            pr.setString(5, pasnum);
    
            int rowsUpdated = pr.executeUpdate();
    
            if (rowsUpdated > 0) {
               JOptionPane.showMessageDialog(this, "Record updated Successfully!");
            } else {
               JOptionPane.showMessageDialog(this, "Record not found or not updated.");
            }
               table_update();
               pn.setText("");
               gen.setText("");
               na.setText("");
               pasn.setText("");
               ph.setText("");
               pn.requestFocus();
               conr.close();
    
         }catch (Exception err) {
             JOptionPane.showMessageDialog(this, err);
         }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
     try {
        Class.forName("com.mysql.jdbc.Driver");
        
        Connection conr = DriverManager.getConnection("jdbc:mysql://localhost/ams", "root", "1234");
        
        String passnum = pasn.getText(); // passnum is the text field where you enter and search
        
        String qry = "SELECT * FROM `managepassenger` WHERE passportnumber = ?";
        
        PreparedStatement pr = conr.prepareStatement(qry);
        pr.setString(1, passnum);
        
        ResultSet rst = pr.executeQuery();
        
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        d.setRowCount(0);
        
        while (rst.next()) {
            Object o[] = {rst.getString("name"), rst.getString("gender"), rst.getString("nationality"), rst.getString("passportnumber"), rst.getString("phone")};
            d.addRow(o);
        }
        
        conr.close();
    } catch (Exception err) {
        JOptionPane.showMessageDialog(this, err);
    }
      if(pasn.getText()== null || pasn.getText().length()== 0){
            table_update();
        }
      pasn.setText("");
      pasn.requestFocus();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try {
           Class.forName("com.mysql.jdbc.Driver");
           Connection conr = DriverManager.getConnection("jdbc:mysql://localhost/ams", "root", "1234");
           Statement st = conr.createStatement();
           String passnum = pasn.getText();

        if (passnum == null || passnum.length() == 0) {
            JOptionPane.showMessageDialog(this, "Empty ID or wrong ID");
        } else {
            String checkQuery = "SELECT * FROM `managepassenger` WHERE passportnumber=?";
            PreparedStatement checkStmt = conr.prepareStatement(checkQuery);
            checkStmt.setString(1, passnum);
            ResultSet checkResult = checkStmt.executeQuery();

            if (checkResult.next()) {
                String deleteQuery = "DELETE FROM `managepassenger` WHERE passportnumber=?";
                PreparedStatement pr = conr.prepareStatement(deleteQuery);
                pr.setString(1, passnum);
                int rowsDeleted = pr.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Data deleted successfully");
                    table_update();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete data");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Record with ID " + passnum + " does not exist");
            }
            pasn.setText("");
            pasn.requestFocus();
            conr.close();
        }
    } catch (Exception err) {
        JOptionPane.showMessageDialog(this, err);
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        Dashboard obj = new Dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePassenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover deleteBtn;
    private javax.swing.JTextField gen;
    private rojeru_san.complementos.RSButtonHover insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField na;
    private javax.swing.JTextField pasn;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField pn;
    private rojeru_san.complementos.RSButtonHover searchBtn;
    private rojeru_san.complementos.RSButtonHover updateBtn;
    // End of variables declaration//GEN-END:variables
}
