/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdama
 */
public class TicketBooking extends javax.swing.JFrame {

    /**
     * Creates new form TicketBooking
     */
    public TicketBooking() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        pi = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        fc = new javax.swing.JTextField();
        frm = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        bookTcktBtn = new rojeru_san.complementos.RSButtonHover();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ticket Booking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ticket Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Passport Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Flight Code");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("From");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("To");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Passenger Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Nationality");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));
        jPanel1.add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 90, -1));
        jPanel1.add(pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));
        jPanel1.add(fc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, -1));
        jPanel1.add(frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, -1));
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 90, -1));
        jPanel1.add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 100, -1));
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 80, -1));

        bookTcktBtn.setText("Book Ticket");
        bookTcktBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTcktBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookTcktBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("BACK");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 50, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ticket Id", "Passport Number", "Flight Code", "From", "To", "Passenger Name", "Gender", "Nationality"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 930, 400));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinemanagement/jet-border.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_update(){
        int c;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conr=DriverManager.getConnection("jdbc:mysql://localhost/ams","root","1234");
            String qry ="SELECT * from ticketbooking";
            
            PreparedStatement pr = conr.prepareStatement(qry);
            
            ResultSet rst= pr.executeQuery();
            
            ResultSetMetaData Rss = rst.getMetaData();

            c =Rss.getColumnCount();

            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
            
            d.setRowCount(0);
            
              while(rst.next()){
                
                Object o[]={rst.getString("ticketid"),rst.getString("passportnumber"),rst.getString("flightcode"),rst.getString("from"),rst.getString("to"),rst.getString("name"),rst.getString("gender"),rst.getString("nationality")};
                d.addRow(o);
                
            }
        }catch(Exception err){
           JOptionPane.showMessageDialog(this, err);
        }
    }
    
    private void bookTcktBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTcktBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");

            Connection conr=DriverManager.getConnection("jdbc:mysql://localhost/ams","root","1234");

            String qry = "insert into ticketbooking values (?,?,?,?,?,?,?,?)";

            PreparedStatement pr=conr.prepareStatement(qry);

            pr.setString(1, pi.getText());
            pr.setString(2, pn.getText());
            pr.setString(3, fc.getText());
            pr.setString(4, frm.getText());
            pr.setString(5, to.getText());
            pr.setString(6, nam.getText());
            pr.setString(7, gen.getText());
            pr.setString(8, na.getText());

            pr.executeUpdate();
            
            int result = JOptionPane.showConfirmDialog(this, "Confirm Booking?", "Select an Option", JOptionPane.YES_NO_CANCEL_OPTION);
           
            
            if(result == JOptionPane.YES_OPTION){
                pi.setText("");
                pn.setText("");
                frm.setText("");
                to.setText("");
                nam.setText("");
                gen.setText("");
                na.setText("");
                pi.requestFocus();
                new Successfully().setVisible(true);
                this.setVisible(false);
            }else
            if(result == JOptionPane.NO_OPTION)
            {
                try {
                     Class.forName("com.mysql.jdbc.Driver");
                     conr = DriverManager.getConnection("jdbc:mysql://localhost/ams", "root", "1234");
                      Statement st = conr.createStatement();
                      String passid = pi.getText();

               if (passid == null || passid.length() == 0) {
                      JOptionPane.showMessageDialog(this, "Empty ID or wrong ID");
                } else {
                         String checkQuery = "SELECT * FROM `ticketbooking` WHERE passengerid=?";
                         PreparedStatement checkStmt = conr.prepareStatement(checkQuery);
                         checkStmt.setString(1, passid);
                         ResultSet checkResult = checkStmt.executeQuery();

            if (checkResult.next()) {
                String deleteQuery = "DELETE FROM `ticketbooking` WHERE ticketid=?";
                pr = conr.prepareStatement(deleteQuery);
                pr.setString(1, passid);
                int rowsDeleted = pr.executeUpdate();

                if (rowsDeleted > 0) {
                    //JOptionPane.showMessageDialog(this, "Data deleted successfully");
                    //table_update();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete data");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Record with ID " + passid + " does not exist");
            }
                pi.setText("");
                pn.setText("");
                frm.setText("");
                to.setText("");
                nam.setText("");
                gen.setText("");
                na.setText("");
                pi.requestFocus();
             conr.close();
        }
    } catch (Exception err) {
        JOptionPane.showMessageDialog(this, err);
    }
 }else{
       Dashboard obj = new Dashboard();
       obj.setVisible(true);
       dispose();
      }
            
            conr.close();
        }catch(Exception err){
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_bookTcktBtnActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        Dashboard obj = new Dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover bookTcktBtn;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField frm;
    private javax.swing.JTextField gen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField na;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField pi;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
